name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your needs.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Core (Agent.Core)
        - Tools (Agent.Tools)
        - AI Integration (Agent.AI)
        - Security (Agent.Security)
        - Orchestration (Agent.Orchestration)
        - Observability (Agent.Observability)
        - Configuration (Agent.Configuration)
        - Communication (Agent.Communication)
        - Registry (Agent.Registry)
        - Dependency Injection (Agent.DI)
        - Samples (Agent.Tools.Samples)
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when... / It would be helpful if... / Currently there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this problem?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        1. When building customer service bots...
        2. When processing large document sets...
        3. When integrating with external APIs...

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API Design
      description: If applicable, provide a rough API design or code example
      render: csharp
      placeholder: |
        // Example of how the feature might be used
        var feature = new YourFeature(config);
        var result = await feature.DoSomethingAsync(input);

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate implementation effort
        - Complex - Significant implementation effort
        - Not sure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that would help us understand and implement this feature

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to implement this feature myself
        - label: I can help with testing once implemented
        - label: I can help with documentation
        - label: I can provide code review

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have considered whether this feature fits with the project's goals and scope
          required: true
        - label: I have provided clear use cases for this feature
          required: true